### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by myovchev** [apostrophecms/form#25]
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

> NOTE - outdated template above - we are running 3.x not 2.x with this module.

## To Reproduce

1. Create a form (piece) in the admin UI
2. Select the "After Submission" editor modal tab 
3. Use the "Edit Email Address(es) for Results" action
4. In the newly opened Array Editor use "Edit Set Conditions for this Notrification"
5. In the newly opened Array Editor add new record
6. Observe the missing translation of `aposForm:emailsConditionsField`, `aposForm:emailsConditionsFieldHelp` and `aposForm:emailsConditionsValue` schema field labels/help

## Expected behavior

A human readable text for fields label and help are expected.

## Describe the bug

Missing definitions of the above mentioned i18n definitions (`i18n/en.js`)

**Comment by BoDonkey** [comment]
Bug Confirmed.
